In [1]:
import numpy as np
array1=np.array([3,2,5,7],dtype='int32')
print(type(array1))

<class 'numpy.ndarray'>


In [2]:
array1.shape

(4,)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(6).dtype

dtype('float64')

In [7]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
array1

array([3, 2, 5, 7])

In [9]:
array1*array1

array([ 9,  4, 25, 49])

In [10]:
array1+array1

array([ 6,  4, 10, 14])

In [11]:
1/array1

array([0.33333333, 0.5       , 0.2       , 0.14285714])

In [12]:
arr=array1[0:2].copy()

In [13]:
arr[0]=5

In [14]:
array1

array([3, 2, 5, 7])

In [16]:
array3=np.array([[1,2,3,4],
       [5,6,7,8]])

In [17]:
array3[0,3]

4