In [1]:
import numpy as np

In [2]:
a=np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [7]:
b=np.array([1,2,3,4,5,6])
b=b.reshape(3,2)

In [8]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
b=b.reshape(6)

In [10]:
b

array([1, 2, 3, 4, 5, 6])

In [12]:
np.argsort(b)

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [13]:
np.argmin(b)

0

In [14]:
np.argmax(b)

5

In [15]:
b=b.reshape(3,2)

In [16]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
np.argsort(b,axis=1)

array([[0, 1],
       [0, 1],
       [0, 1]], dtype=int32)

In [18]:
np.argsort(b,axis=0)

array([[0, 0],
       [1, 1],
       [2, 2]], dtype=int32)

In [19]:
np.argmin(b)

0

In [20]:
np.argmax(b)

5